# Site settings
title: Victor Duan's Site
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Quick try on jekyll.
baseurl: "/test_jekyll" # the subpath of your site, e.g. /blog/
url: "http://vduan.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
